### ISSUE TITLE
Potential security issue with your page

### ISSUE THREAD

**Issue by rakovskij-stanislav** [painebenjamin/app.enfugue.ai#1]
Hello! I haven't found your email or social network page, so I'll write here

Your project on pypi named `enfugue` probably reveals a security problem:
`enfugue/util/signature.py` has a link to your private keys and certificates, they are encoded here: `enfugue/util/security.py`

<img width="885" alt="image" src="https://github.com/painebenjamin/app.enfugue.ai/assets/25303578/bc5575ad-e0b3-42fc-8c45-e636d0d25d2d">

This developmenttools-like code not so easy to deobfuscate, so we have one private key and two certs.

I did not check what's private key related (your ssh, your github or other things)
The certs are:
```
Serial Number:
            36:b7:59:6f:e1:72:21:c6:9c:aa:d0:0c:5b:be:a5:bb
Signature Algorithm: sha256WithRSAEncryption
Issuer: C = US, ST = Texas, L = Houston, O = SSL Corporation, CN = SSL.com RSA SSL subCA
Validity
    Not Before: Jun 27 20:04:02 2023 GMT
    Not After : Jul 27 20:04:02 2024 GMT
Subject: C = US, ST = Texas, L = Houston, O = SSL Corporation, CN = SSL.com RSA SSL subCA
```
```
Serial Number: 691281723435976700 (0x997ed109d1f07fc)
Issuer: C = US, ST = Texas, L = Houston, O = SSL Corporation, CN = SSL.com Root Certification Authority RSA
Validity
            Not Before: Feb 12 18:48:52 2016 GMT
            Not After : Feb 12 18:48:52 2031 GMT
Subject: CN = app.enfugue.ai
```

You made some steps for extra encoding it so I can suppose this private key and certs are valuable and should not be obtainable by clients. If it is right, I suggest you to make steps to change them and avoid their leak to client-side.

**Comment by painebenjamin** [comment]
Hello,

Thanks for the report. Unfortunately by the nature of Enfugue being a self-hosted server, there is no way to effectively store any kind of secret such that it cannot be retrieved by an intrepid user such as yourself, so it was understood from the get-go that this secret would be need to be exposed. Since `app.enfugue.ai` is just a loopback, and that certificate can only effectively be used to sign requests from yourself to yourself, the security risk is minimal.
