### ISSUE TITLE
The invocation was terminated prematurely

### ISSUE THREAD

**Issue by rostamiani** [painebenjamin/app.enfugue.ai#45]
I'm testing enfuge 0.1.2 in my Laptip.
When I click ENFUGE initialization never ends
I found out that some requests to server is happenning repeatedly and this error is in Network tab of browser console in response of `/api/invocation`:
```json
{
  "meta": { "params": {} },
  "data": [
    {
      "status": "error",
      "uuid": "850ea9228afa4598a7ab6b9f82c5549c",
      "message": "The invocation was terminated prematurely"
    },
    {
      "id": 3,
      "uuid": "33cf948fd65746dc86666b9d8c739e65",
      "status": "processing",
      "progress": null,
      "step": null,
      "duration": 53.501603,
      "total": null,
      "images": null,
      "rate": null
    }
  ]
}
```
This is my GPU info:
```json
{
  "gpu": {
    "driver": "511.69",
    "name": "NVIDIA GeForce MX330",
    "load": 0.03,
    "temp": 51,
    "memory": {
      "free": 1983,
      "total": 2048,
      "used": 0,
      "util": 0
    }
  }
}

```

**Comment by painebenjamin** [comment]
Hello, thank you for the report!

The invocation being terminated prematurely should only occur if you click the "Stop" button (or otherwise turn off the engine.) I'm guessing you may have terminated it after a minute of no data - I am testing a release candidate now that improves transparency when the backend needs to perform some kind of long-running action, like downloading a new model.

With that being said, I am not sure if you will be able to use Enfugue (or Stable Diffusion in general) with the MX330. 2GB of VRAM is well below the recommended lower bound of 8GB - I've successfully used machines with 6GB of VRAM, but I've never tried with anything less. You will receive an error indicating memory has run out if/when you encounter this.
