### ISSUE TITLE
0.24 link and TensorRT (2 things)

### ISSUE THREAD

**Issue by RandomKaos999** [painebenjamin/app.enfugue.ai#82]
Hey,

Had an email that tag 0.2.4 was available, by the time I got to try it out, the link was no longer functional/working. Assuming you pulled it, but just in case.. its not available.

TensorRT support. It's baffling me getting it even available for the first time.

I've downloaded 0.2.3 tensorRT zips, extracted them, extracted the zip's into a new folder. No new menu options or 0/3 icon that I can see to build.
Installed CUDA 11.7.1, from link on main github, extracted CudaNN and add to user path, extracted Tensor files and added to path. Restarted Enfugue, and still no options visible. I cant see anything in the logs relevant, and its baffling me. How do I know which part isn't right, what its looking for that isn't there? or have things changed since the main text was written?

I might be being stupid, and just needs another reboot, so Ill try that in a second, but just in case, posting here...

**Comment by painebenjamin** [comment]
Hello!

Yes, very sorry, that release was not intended to go out yet. It will be out no later than tomorrow.

With regards to TensorRT, it has not changed - at time of release TensorRT was at version `8.6.1`, and that hasn't changed yet. `9.0.0` is in development with significant improvements, but unfortunately it's not ready.

What _did_ change from release though was that I made on-the-fly configuration available, which is how I think most people are using Enfugue now. That unfortunately does not work with TensorRT, as TRT bakes all of the network weights in when it's compiled, so in order to not have the user accidentally spend 20 minutes compiling an engine only to invalidate it by changing a LoRA scale from `1.0` to `0.99`, compiling engines is only done with pre-configured sets.

The documentation was absolutely not clear enough about this, so I changed it to read the following:

> To use TensorRT, first **create a pre-configured model as detailed above.** TensorRT requires all weights be "frozen" prior to engine compilation - which means that certain parameters must be made static and unchanging (or else you must re-compile the engine.) These are:
> 
> 1. The checkpoint (base model)
> 2. The size of the TensorRT engine (default 512px)
> 3. LoRA and their scales
> 4. LyCORIS and their scales
> 5. Textual Inversion
> 
> Since this is the case, you **must** use model configuration sets to compile TensorRT engines. After creating a configuration set and selecting a model, you will see a small icon next to the model name with a number. This is the number of TensorRT engines that are prepared...<etc.>

Please ensure you're doing this first. If that still doesn't get you moving (it's entirely possible there is still something else wrong,) it would be very helpful for you to provide your engine logs, located by default at `C:\Users\<Username>\.cache\enfugue-engine.log` (substituting `C:\` for your installation drive letter.) Logs are redacted to not include your prompts for the sake of privacy, but your username and the file path to your installation directory will still be visible so please remove them if you do not wish them to be made public.

**Comment by RandomKaos999** [comment]
Sorted it after you pointed out the log location, found that it was trying to find "cudnn64_8.dll" - however, it wasn't finding it due to the instructions listed, it said to add \lib to the path for CudaNN, however, the dll file is located in \bin.

Trivial thing really :)

Thanks for the reply. I'll go and give this a whirl now. Assuming it builds, the icon is there at least now with 0/3.

Might be worth in future to get these things to present in the engine log in the application as well.

Oh and random request - any chance of improving the Lora add option, and if you are going for it, please allow browsing by directory and same filenames. I'm sure i am not the only one that regenerates Lora's with small changes and no change in filename, but different folders. A1111 drives me crazy with its current Lora listings.
But... If I add a path to the settings, say H:\Lora, and I have a lora in H:\Lora\style\pink\unicorn.safetensors, then it will find unicorn.safetensors in the list in Enfugue, but won't actually work and present an error. If you need sample log output for that, let me know.

**Comment by painebenjamin** [comment]
I'll take small victories on it showing up! Definitely let me know how it works out.

Thank for you the feature request. A very significant effort has been made in `0.2.4` to improve finding and loading of models, especially in situations where enfugue is colocated with an A1111/Comfy installation - specifically, arbitrarily nested directories (including symlinks) are now supported and erroneous files are excluded, showing only `.safetensors`, `.pth`, `.pt`, `.bin` or `.ckpt` files. So I *sort of* have a solution for you already!

I say sort of, however, becase it will find the first file that matches the name, so if you have a number of files of the same name in different directories,`0.2.4` won't do well with that. Sorry about that, but it's definitely something I can mull over to figure out a good solution for.

I'll leave this ticket open for now in case TensorRT doesn't go as expected. Thank you for using Enfugue!

**Comment by MysticDaedra** [comment]
My cudnn_windows download didn't come with a /lib or /bin folder... just cudnn_windows with a bunch of .dll files in it. Did I mess something up?

**Comment by RandomKaos999** [comment]
Possibly, I downloaded the cudnn-windows-x86_64-8.9.5.29_cuda11-archive.zip package from Nvidia and it came with the following structure in the zip file:

![image](https://github.com/painebenjamin/app.enfugue.ai/assets/138111560/5469869e-a9e5-4ca1-a87f-ec0cfba0d767)
