### ISSUE TITLE
Lora Filepath Restrictions/Issue

### ISSUE THREAD

**Issue by RandomKaos999** [painebenjamin/app.enfugue.ai#85]
Hi, me again, this time with a potential Lora/filesystem issue.

I have a folder setup H:\AIStuff\Generations\Lora - contains subfolders etc with Lora's I tinker with. 
e.g
`H:\AIStuff\Generations\Lora\People\<name>\optimiser\<different folder name>\*.safetensor`

If I add the folder H:\AIStuff\Generations\Lora to Enfugue in the "Installation settings", it does indeed list them on the software, however, when going to run inference:

2023-10-05 16:19:25,629 [enfugue] DEBUG (manager.py:2369) Adding LoRA H:\AIStuff\Generations\Lora\People\test05102023.safetensors to pipeline with weight 1.0
2023-10-05 16:19:25,971 [enfugue] ERROR (process.py:381) Received error builtins.FileNotFoundError: No such file or directory: "H:\\AIStuff\\Generations\\Lora\\People\\test05102023.safetensors"

However, the actual full path would of been H:\AIStuff\Generations\Lora\People\CurrentTest\DAdaptation\ModelWeight0.4\test05102023.safetensors

Edit: This was on 0.2.3, ill download 0.2.4 and try that just to confirm it on there too.

**Comment by painebenjamin** [comment]
Hello! Yes, please it give a shot on 0.2.4. This should explicitly be fixed in that version.

**Comment by painebenjamin** [comment]
Hello @RandomKaos999!

Thank you for reporting this. Since this was an essential fix for the launch on RunDiffusion, I scrambled and snuck in a fix.

I believe you're using the portable binary - I'm sorry to ask you to download yet another thing, but if you could, please re-download the `0.2.4` release to get the fix. If you're managing your own environment, you can run `pip install --upgrade enfugue` or `pip install enfugue==0.2.4.post1`.

**Comment by RandomKaos999** [comment]
Re-downloaded and tested, confirmed now working properly with pre-configured models :)
